# Generated by Django 4.1.7 on 2023-03-05 09:42

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(path=pathlib.PurePosixPath('/Users/paddy/Desktop/starwars-characters/starwars/collection_files'))),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
